version: "3"

services:
  db:
    image: postgres:10-alpine
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=TemporaryPassword
    ports:
      - 5432:5432
    